//! Preset renderer inventory extracted from the FCL release APK (task 9 addendum).
//!
//! `FCL-release-1.3.2.7-arm64-v8a.apk` bundles the actual OpenGL(ES)
//! translation `.so` files our built-in renderers wrap. This module snapshots
//! that inventory (file names, uncompressed sizes, SHA-256 and SHA-1) so the
//! launcher can *preset* the renderers it ships, inject the right native libs
//! and later verify (integrity) that a deployed `nativeLibraryDir` actually
//! contains the expected renderer binaries — without carrying the 172 MB APK
//! at runtime.
//!
//! The snapshot is embedded as `const` data below (generated by
//! `docs/gen_fcl_apk_manifest.py` from the APK); see [`FCL_APK_RENDERER_MANIFEST`]
//! and [`preset_registry`].

use std::path::Path;

use crate::plugins::native_lib::{LibVerify, NativeLib};
use crate::plugins::renderer::{renderer_plugin, RendererRegistry, TrustLevel};
use crate::runtime::Abi;

/// One native library the FCL APK bundles for a renderer, with integrity info.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ApkLibEntry {
    pub file_name: &'static str,
    pub size: u64,
    pub sha256: &'static str,
    pub sha1: &'static str,
}

/// A renderer preset extracted from the FCL APK (arm64-v8a).
#[derive(Debug, Clone)]
pub struct FclApkRenderer {
    pub id: &'static str,
    pub display_name: &'static str,
    pub libs: &'static [ApkLibEntry],
}

/// The embedded FCL APK renderer inventory.
#[derive(Debug, Clone)]
pub struct FclApkRendererManifest {
    pub apk_name: &'static str,
    pub abi: Abi,
    pub renderers: &'static [FclApkRenderer],
}

/// Renderer native-lib inventory bundled in `FCL-release-1.3.2.7-arm64-v8a.apk`.
///
/// Generated by inspecting the APK's `lib/arm64-v8a/*.so` entries; the
/// `display_name`s and renderer `id`s mirror the built-in [`RendererPlugin`]s.
pub const FCL_APK_RENDERER_MANIFEST: FclApkRendererManifest = FclApkRendererManifest {
    apk_name: "FCL-release-1.3.2.7-arm64-v8a.apk",
    abi: Abi::Arm64V8a,
    renderers: &[
        FclApkRenderer {
            id: "opengles2",
            display_name: "GL4ES 1.1.4",
            libs: &[
                ApkLibEntry {
                    file_name: "libgl4es_114.so",
                    size: 2649480u64,
                    sha256: "3dbcc87baae1436f2affb923eda053d7e256f0aa032654452e2b2092566f6b24",
                    sha1: "325c0817f48b2b298687421bb59ad0a0c69f5dd1",
                },
                ApkLibEntry {
                    file_name: "libglapi.so",
                    size: 404344u64,
                    sha256: "4e790174e44ce55507b522840e757dba54d1c838d2df9650cfc33e41b616388b",
                    sha1: "ea618b8961beae976353405be50285a55506ec39",
                },
                ApkLibEntry {
                    file_name: "libglxshim.so",
                    size: 261600u64,
                    sha256: "de28da7dad5c44377e65b1ff3d119a5ac382563b4df427aea6ad5d51121924ec",
                    sha1: "f85e0f60c84aece9cc5e47c92471ef6d121e2dcb",
                },
            ],
        },
        FclApkRenderer {
            id: "opengles2_ng",
            display_name: "NG-GL4ES",
            libs: &[
                ApkLibEntry {
                    file_name: "libng_gl4es.so",
                    size: 6768224u64,
                    sha256: "cfee8bf238fc508478454c2daf19b518182827b426d5d4556f1e93a0ad348ea7",
                    sha1: "3c2bf335a8dc466a686642f71bc25228898f9e52",
                },
                ApkLibEntry {
                    file_name: "libglapi.so",
                    size: 404344u64,
                    sha256: "4e790174e44ce55507b522840e757dba54d1c838d2df9650cfc33e41b616388b",
                    sha1: "ea618b8961beae976353405be50285a55506ec39",
                },
            ],
        },
        FclApkRenderer {
            id: "opengles2_vgpu",
            display_name: "VirGL / vgpu",
            libs: &[
                ApkLibEntry {
                    file_name: "libvgpu.so",
                    size: 1288192u64,
                    sha256: "253c2e03f90d775b51f3690bc24b3e0d67304e6e63b65f0f1ac80cda7a9e2689",
                    sha1: "492f7c6d4440c0b4041acc70fa20944d8ae10637",
                },
                ApkLibEntry {
                    file_name: "libvirgl_test_server.so",
                    size: 1420480u64,
                    sha256: "1e72f9754210061724e9ebed8d2ec20ba58c2c121518986d04150a46a16c723e",
                    sha1: "869936c8c79f91f587a87882a116ca2287b83255",
                },
                ApkLibEntry {
                    file_name: "libEGL_mesa.so",
                    size: 302520u64,
                    sha256: "8fa8b21185a75506e28cd7020d9b8551c013afc1f3b227c028e038516c173f1e",
                    sha1: "3f22cd5c3dc453e13c59c898400d5df8ce15aedf",
                },
            ],
        },
        FclApkRenderer {
            id: "opengles3_desktopgl_zink_kopper",
            display_name: "Zink (Mesa)",
            libs: &[
                ApkLibEntry {
                    file_name: "libOSMesa_8.so",
                    size: 13742616u64,
                    sha256: "08710cd5f1aa8763b1106143b647162c6b73fa38d04663147d63aa48f9341d81",
                    sha1: "25a8487f3fd9edb3fcc7d3e0a7d2aff599f67922",
                },
                ApkLibEntry {
                    file_name: "libzink_dri.so",
                    size: 12506640u64,
                    sha256: "585fbd021a1195465d1f42c2be8d8aa3b770bda4155d4c7dd16a9dac08f3fff0",
                    sha1: "b7fd2b2efb03c07eabd75ed5f08ed63c66d45fda",
                },
                ApkLibEntry {
                    file_name: "libvulkan_freedreno.so",
                    size: 9414112u64,
                    sha256: "09a486467b404ec9bcd158ea5fe9e1499c0e46c7e56a2c4c0f415f04b7eb0b5a",
                    sha1: "f9cbbc18a59aecb3c6efbb70433ba54ae82e5f4c",
                },
                ApkLibEntry {
                    file_name: "libEGL_mesa.so",
                    size: 302520u64,
                    sha256: "8fa8b21185a75506e28cd7020d9b8551c013afc1f3b227c028e038516c173f1e",
                    sha1: "3f22cd5c3dc453e13c59c898400d5df8ce15aedf",
                },
            ],
        },
        FclApkRenderer {
            id: "opengles3_angle",
            display_name: "ANGLE",
            libs: &[
                ApkLibEntry {
                    file_name: "libGLESv2_angle.so",
                    size: 5717200u64,
                    sha256: "0e0d9347086282008752b9bca0f87a8bb912b22129b6374c1a14a8aaf6fad28c",
                    sha1: "c7facbd7f8191b74f5c9f6c005ae4780b1b0d629",
                },
                ApkLibEntry {
                    file_name: "libEGL_angle.so",
                    size: 297352u64,
                    sha256: "a34c326b3702bf1d32e9081a6cb2b1e01514b85336f8c3f34bc9a73ee203de51",
                    sha1: "a47d261f0f1ccf432faa9736ded4bc4556e2c973",
                },
                ApkLibEntry {
                    file_name: "libspirv-cross-c-shared.so",
                    size: 3463112u64,
                    sha256: "9f7a21ae51739d8cfe8b3a0ebb8d6e55cfea1cf95effbf991a13ca50436e185a",
                    sha1: "dc63c526f1f2059fb0ef4eab61c8be0ca7cace02",
                },
            ],
        },
    ],
};

impl FclApkRendererManifest {
    /// The preset renderers in this APK.
    pub fn renderers(&self) -> &[FclApkRenderer] {
        self.renderers
    }

    /// Every distinct `.so` file name across all preset renderers.
    pub fn all_lib_names(&self) -> Vec<&'static str> {
        let mut out: Vec<&'static str> = Vec::new();
        for r in self.renderers {
            for l in r.libs {
                if !out.contains(&l.file_name) {
                    out.push(l.file_name);
                }
            }
        }
        out
    }

    /// Verify an on-disk native lib directory against this manifest.
    ///
    /// For each preset renderer lib present under `native_lib_dir`, checks
    /// the file size (and SHA-1 when recorded). Returns the per-lib results.
    pub fn verify_native_lib_dir(&self, native_lib_dir: &Path) -> Vec<(String, LibVerify)> {
        let mut out = Vec::new();
        for r in self.renderers {
            for l in r.libs {
                let path = native_lib_dir.join(l.file_name);
                let nl = NativeLib {
                    file_name: l.file_name.to_string(),
                    abi: None,
                    source: crate::plugins::native_lib::NativeLibSource::NativeLibDir,
                    load_order: 0,
                    optional: true,
                    expected_size: Some(l.size),
                    expected_sha256: Some(l.sha256.to_string()),
                    expected_sha1: Some(l.sha1.to_string()),
                };
                let res = match nl.verify_on_disk(&path) {
                    Ok(v) => v,
                    Err(_) => LibVerify::Missing,
                };
                out.push((format!("{}::{}", r.id, l.file_name), res));
            }
        }
        out
    }
}

/// The embedded manifest singleton.
pub fn manifest() -> &'static FclApkRendererManifest {
    &FCL_APK_RENDERER_MANIFEST
}

/// Build a [`RendererRegistry`] preset from the FCL APK inventory.
///
/// Each preset renderer carries the *actual* native libs the APK ships
/// (the primary `gl_libname` is required; dependency `.so`s are optional)
/// together with their sizes / hashes for integrity verification, and is
/// scoped to `arm64-v8a` (the only ABI this APK provides).
pub fn preset_registry() -> RendererRegistry {
    use crate::launch::options::Renderer;
    let mut reg = RendererRegistry::builtin();
    for r in manifest().renderers() {
        let base = match r.id {
            "opengles2" => Renderer::Gl4es,
            "opengles2_ng" => Renderer::NgGl4es,
            "opengles2_vgpu" => Renderer::VirGl,
            "opengles3_desktopgl_zink_kopper" => Renderer::Zink,
            "opengles3_angle" => Renderer::Angle,
            _ => continue,
        };
        let mut plugin = renderer_plugin(base);
        plugin.native_libs = r
            .libs
            .iter()
            .map(|e| {
                let mut nl = NativeLib::in_native_lib_dir(e.file_name);
                nl.expected_size = Some(e.size);
                nl.expected_sha256 = Some(e.sha256.to_string());
                nl.expected_sha1 = Some(e.sha1.to_string());
                // primary lib (the one LWJGL dlopens) is required; deps optional
                if e.file_name != plugin.gl_libname {
                    nl.optional = true;
                }
                nl
            })
            .collect();
        plugin.supported_abis = vec![Abi::Arm64V8a];
        plugin.trust = TrustLevel::System;
        reg.register(plugin);
    }
    reg
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;
    use std::fs::File;
    use std::path::PathBuf;

    use zip::ZipArchive;

    use crate::plugins::renderer::RendererRegistry;

    #[test]
    fn preset_registry_has_five_with_integrity() {
        let reg = preset_registry();
        assert_eq!(reg.all().len(), 5);
        for p in reg.all() {
            assert_eq!(p.trust, TrustLevel::System);
            assert_eq!(p.supported_abis, vec![Abi::Arm64V8a]);
            assert!(!p.native_libs.is_empty());
            for nl in &p.native_libs {
                // every preset lib carries the APK integrity metadata
                assert!(nl.expected_size.is_some(), "{} missing size", nl.file_name);
                assert!(nl.expected_sha1.is_some(), "{} missing sha1", nl.file_name);
                assert!(
                    nl.expected_sha256.is_some(),
                    "{} missing sha256",
                    nl.file_name
                );
                // the primary lib (the one LWJGL dlopens) is required; deps optional
                if nl.file_name == p.gl_libname {
                    assert!(!nl.optional);
                } else {
                    assert!(nl.optional);
                }
            }
        }
    }

    #[test]
    fn manifest_primary_lib_matches_builtin_gl_libname() {
        let reg = RendererRegistry::builtin();
        for r in manifest().renderers() {
            let builtin = reg
                .get(r.id)
                .unwrap_or_else(|| panic!("manifest id `{}` must map to a built-in", r.id));
            let primary = r.libs.iter().find(|l| l.file_name == builtin.gl_libname);
            assert!(
                primary.is_some(),
                "manifest renderer `{}` must list its primary lib `{}`",
                r.id,
                builtin.gl_libname
            );
        }
    }

    #[test]
    fn manifest_lib_names_are_all_present_in_apk_layout() {
        // Every preset lib name must be a bare `lib*.so` (no surprises).
        for name in manifest().all_lib_names() {
            assert!(
                name.starts_with("lib") && name.ends_with(".so"),
                "bad lib name {name}"
            );
        }
    }

    #[test]
    fn cross_check_manifest_against_apk() {
        // Gated: only runs when the FCL release APK is available on disk. Opens
        // the APK as a zip and confirms every manifest lib (name + uncompressed
        // size) is actually present in `lib/arm64-v8a/`. This proves the preset
        // is truthful rather than hand-maintained.
        let candidate = std::env::var("FCL_APK_PATH")
            .unwrap_or_else(|_| "../../../fcl-apk/FCL-release-1.3.2.7-arm64-v8a.apk".to_string());
        let path = PathBuf::from(candidate);
        if !path.exists() {
            eprintln!("skipping cross-check: APK not found at {}", path.display());
            return;
        }
        let file = File::open(&path).expect("open FCL APK");
        let mut archive = ZipArchive::new(file).expect("read FCL APK as zip");
        let mut apk_libs: HashMap<String, u64> = HashMap::new();
        for i in 0..archive.len() {
            let e = archive.by_index(i).expect("zip entry");
            let name = e.name().to_string();
            if let Some(rest) = name.strip_prefix("lib/arm64-v8a/") {
                if name.ends_with(".so") {
                    apk_libs.insert(rest.to_string(), e.size());
                }
            }
        }
        for r in manifest().renderers() {
            for l in r.libs {
                let actual = apk_libs.get(l.file_name).unwrap_or_else(|| {
                    panic!(
                        "manifest lib {} (renderer `{}`) not found in APK",
                        l.file_name, r.id
                    )
                });
                assert_eq!(
                    *actual, l.size,
                    "uncompressed size mismatch for {} in APK",
                    l.file_name
                );
            }
        }
    }
}
