//! Mobile Glues renderer plugin (task 8).
//!
//! Players explicitly asked for a built-in Mobile Glues renderer (the
//! GLES-over-Vulkan OpenGL(ES) translation stack; the APK is already bundled at
//! `mobile_gules_apk/MobileGlues_2.0.0.apk`). This module turns that APK into a
//! pluggable [`RendererPlugin`] in the same spirit as FCL's `RendererPlugin` and
//! Zalith's `NativeLibPlugin` / `VerifiedPluginLoad`:
//!
//! * [`MOBILEGLUES_APK_LIBS`] — the embedded integrity inventory of the GL
//!   translation native libraries the APK bundles (`libmobileglues.so` and its
//!   two helpers), with uncompressed sizes + SHA-1/SHA-256 taken from the APK.
//!   The safe-loading pipeline (`validation`) uses them to *verify* the deployed
//!   libs (tamper / truncation) and to preflight before spawning the JVM.
//! * [`parse_mobileglues_apk`] — re-reads the on-device APK (e.g. after an OTA
//!   update) to refresh that inventory from the actually shipped package.
//! * [`mobileglues_plugin`] / [`mobileglues_plugin_from_apk`] — build the
//!   [`RendererPlugin`] descriptor, wire the native-library injection and attach
//!   the integrity metadata so the loader can trust it.
//! * [`apply_mobileglues_integrity`] — fold the APK integrity metadata into a
//!   [`RendererPlugin`] produced by [`crate::plugins::renderer_plugin`], keeping
//!   the single-source-of-truth descriptor (the `Renderer` enum) in lock-step.

use std::io::Read;
use std::path::Path;

use sha1::{Digest as _, Sha1};
use sha2::Sha256;

use crate::error::{RcError, RcResult};
use crate::plugins::native_lib::NativeLib;
use crate::plugins::renderer::{RendererPlugin, RendererRegistry, TrustLevel, WindowingBackend};
use crate::runtime::Abi;

/// The bundled Mobile Glues APK asset name (task 8).
pub const MOBILEGLUES_APK_NAME: &str = "MobileGlues_2.0.0.apk";

/// One GL translation native library the Mobile Glues APK ships, with integrity.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MobileGluesLib {
    /// File name inside `lib/<abi>/` (no path separator; anti-traversal safe).
    pub file_name: &'static str,
    /// Uncompressed size in bytes.
    pub size: u64,
    /// SHA-256 hex of the lib's bytes.
    pub sha256: &'static str,
    /// SHA-1 hex of the lib's bytes (runtime-verifiable with the `sha1` crate).
    pub sha1: &'static str,
    /// Whether this lib is the one LWJGL `dlopen`s (required); helpers optional.
    pub primary: bool,
}

/// Integrity inventory of the GL translation native libraries bundled in
/// `MobileGlues_2.0.0.apk` (arm64-v8a).
///
/// Generated by inspecting the APK's `lib/arm64-v8a/*.so` entries. `libmobileglues.so`
/// is the primary GLES driver LWJGL `dlopen`s; the other two are runtime helpers
/// (`libmobileglues_info_getter.so`, `libandroidx.graphics.path.so`) that are
/// optional for launching.
pub const MOBILEGLUES_APK_LIBS: &[MobileGluesLib] = &[
    MobileGluesLib {
        file_name: "libmobileglues.so",
        size: 6120864u64,
        sha256: "3c87948b9b362ad2b6cf48e43ea181014f9999fe4607db0eff8b9db52d385fcd",
        sha1: "4b246f3a0601873b29ab2d22bf63b5962f5ce128",
        primary: true,
    },
    MobileGluesLib {
        file_name: "libmobileglues_info_getter.so",
        size: 925520u64,
        sha256: "cee841050fb9c86dd7da5ba0e52a46345f872420fcbfc63f817288df487f6b5b",
        sha1: "4f2a0d00e092fea3a6df9a3c7ed04aeb44533828",
        primary: false,
    },
    MobileGluesLib {
        file_name: "libandroidx.graphics.path.so",
        size: 10096u64,
        sha256: "41e9a793c43a0f4fddb19e33f346bace464f30f888ba7b9eaf96294ea115bfb6",
        sha1: "d7c17fcb44b30a6efe89d436aa102abe52e008a6",
        primary: false,
    },
];

/// The GL translation native libraries Mobile Glues contributes (file names, in
/// loader order: primary first, then helpers).
pub fn gl_translation_native_libs() -> &'static [&'static str] {
    &[
        "libmobileglues.so",
        "libmobileglues_info_getter.so",
        "libandroidx.graphics.path.so",
    ]
}

/// Fold the embedded APK integrity inventory into `plugin`'s native libs.
///
/// Each native lib is resolved from the app's `nativeLibraryDir`; the primary
/// `libmobileglues.so` is required, the helpers optional. Sizes + SHA-1/SHA-256
/// are attached so the safe-loading pipeline can verify the deployed binaries.
pub fn apply_mobileglues_integrity(plugin: &mut RendererPlugin) {
    for lib in &mut plugin.native_libs {
        if let Some(meta) = MOBILEGLUES_APK_LIBS
            .iter()
            .find(|m| m.file_name == lib.file_name)
        {
            lib.expected_size = Some(meta.size);
            lib.expected_sha1 = Some(meta.sha1.to_string());
            lib.expected_sha256 = Some(meta.sha256.to_string());
        }
    }
}

/// Build the Mobile Glues [`RendererPlugin`] from the embedded APK inventory
/// (task 8). System-trusted; native libs resolved from the app native-lib dir.
pub fn mobileglues_plugin() -> RendererPlugin {
    let mut plugin = RendererPlugin::builder("mobile_glues", "Mobile Glues 2.0.0")
        .gl_libname("libmobileglues.so")
        .backend(WindowingBackend::GlSurface)
        .env(vec![
            // Mobile Glues is a GLES-over-Vulkan translation of desktop GL; it
            // consumes the same GL compat knobs GL4ES does for Minecraft colour
            // / extension compatibility, applied by the launch engine as part of
            // the base renderer environment.
            ("LIBGL_ES".into(), "2".into()),
            ("LIBGL_USE_MC_COLOR".into(), "1".into()),
            ("LIBGL_NOERROR".into(), "1".into()),
        ])
        .native_lib(NativeLib::in_native_lib_dir("libmobileglues.so"))
        .native_lib(NativeLib::in_native_lib_dir("libmobileglues_info_getter.so").optional(true))
        .native_lib(NativeLib::in_native_lib_dir("libandroidx.graphics.path.so").optional(true))
        .trust(TrustLevel::System)
        .author("mobile_gules")
        .build();
    apply_mobileglues_integrity(&mut plugin);
    plugin
}

/// Re-parse the Mobile Glues APK, extracting the integrity metadata for every GL
/// translation native library present under `lib/<abi>/`.
///
/// Mirrors FCL's APK-manifest extraction but runs against the on-device APK so
/// the launcher can refresh (or freshly verify) the inventory after an update.
pub fn parse_mobileglues_apk(apk_path: &Path, abi: Abi) -> RcResult<Vec<MobileGluesLib>> {
    let file = std::fs::File::open(apk_path).map_err(|e| {
        RcError::Other(format!(
            "cannot open Mobile Glues APK {}: {e}",
            apk_path.display()
        ))
    })?;
    let mut archive = zip::ZipArchive::new(file).map_err(|e| {
        RcError::Other(format!(
            "cannot read Mobile Glues APK {}: {e}",
            apk_path.display()
        ))
    })?;
    let prefix = format!("lib/{}/", abi.as_android_abi());
    let mut out: Vec<MobileGluesLib> = Vec::new();
    for i in 0..archive.len() {
        let mut entry = archive.by_index(i).map_err(|e| {
            RcError::Other(format!(
                "cannot read entry {i} of {}: {e}",
                apk_path.display()
            ))
        })?;
        let name = entry.name().to_string();
        if !name.starts_with(&prefix) {
            continue;
        }
        let base_borrowed = match name.rsplit('/').next() {
            Some(b) => b,
            None => continue,
        };
        // Resolve to the static `&'static str` from the known GL translation lib
        // set (so the parsed inventory shares the same `file_name` type as the
        // embedded const without leaking).
        let base: &'static str = match gl_translation_native_libs()
            .iter()
            .find(|m| **m == base_borrowed)
        {
            Some(m) => m,
            None => continue,
        };
        let mut data = Vec::with_capacity(entry.size() as usize);
        entry
            .read_to_end(&mut data)
            .map_err(|e| RcError::Other(format!("cannot read {} from APK: {e}", name)))?;
        let sha1_hex = {
            let mut h = Sha1::new();
            h.update(&data);
            hex(&h.finalize())
        };
        let sha256_hex = {
            let mut h = Sha256::new();
            h.update(&data);
            hex(&h.finalize())
        };
        out.push(MobileGluesLib {
            file_name: base,
            size: data.len() as u64,
            sha256: Box::leak(sha256_hex.into_boxed_str()),
            sha1: Box::leak(sha1_hex.into_boxed_str()),
            primary: base == "libmobileglues.so",
        });
    }
    if out.is_empty() {
        return Err(RcError::Other(format!(
            "Mobile Glues APK {} contains no GL translation libs for ABI {}",
            apk_path.display(),
            abi.as_android_abi()
        )));
    }
    Ok(out)
}

fn hex(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push_str(&format!("{:02x}", b));
    }
    s
}

/// Build the Mobile Glues [`RendererPlugin`] by re-parsing the on-device APK.
///
/// The integrity metadata comes from the APK itself (fresh, post-update), so
/// the safe-loading pipeline verifies the *actually deployed* binaries. Returns
/// [`mobileglues_plugin`] (embedded inventory) as a base, then overlays the
/// freshly parsed sizes / hashes.
pub fn mobileglues_plugin_from_apk(apk_path: &Path, abi: Abi) -> RcResult<RendererPlugin> {
    let libs = parse_mobileglues_apk(apk_path, abi)?;
    let mut plugin = mobileglues_plugin();
    for lib in &mut plugin.native_libs {
        if let Some(meta) = libs.iter().find(|m| m.file_name == lib.file_name) {
            lib.expected_size = Some(meta.size);
            lib.expected_sha1 = Some(meta.sha1.to_string());
            lib.expected_sha256 = Some(meta.sha256.to_string());
        }
    }
    Ok(plugin)
}

/// Parse the bundled Mobile Glues APK and fold its GL translation native libs
/// into `reg`, refreshing (or inserting) the `mobile_glues` plugin with the
/// integrity metadata taken from the *actually deployed* package (task 8).
///
/// This is the deploy-time half of the integration: the launcher calls it after
/// extracting / updating the APK so the discoverable, user-selectable catalogue
/// always reflects the on-device binaries, and the safe-loading pipeline verifies
/// them. A missing APK is surfaced as an error rather than silently trusted.
pub fn register_mobileglues_from_apk(
    mut reg: RendererRegistry,
    apk_path: &Path,
    abi: Abi,
) -> RcResult<RendererRegistry> {
    let plugin = mobileglues_plugin_from_apk(apk_path, abi)?;
    reg.register(plugin);
    Ok(reg)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::launch::options::Renderer;

    #[test]
    fn embedded_integrity_is_well_formed() {
        assert_eq!(MOBILEGLUES_APK_LIBS.len(), 3);
        let primary = MOBILEGLUES_APK_LIBS.iter().find(|m| m.primary).unwrap();
        assert_eq!(primary.file_name, "libmobileglues.so");
        assert!(MOBILEGLUES_APK_LIBS
            .iter()
            .all(|m| m.sha1.len() == 40 && m.sha256.len() == 64));
        // the primary lib is the one LWJGL dlopens
        assert!(MOBILEGLUES_APK_LIBS.iter().filter(|m| m.primary).count() == 1);
    }

    #[test]
    fn plugin_is_system_trusted_with_integrity() {
        let p = mobileglues_plugin();
        assert_eq!(p.id, "mobile_glues");
        assert_eq!(p.gl_libname, "libmobileglues.so");
        assert_eq!(p.trust, TrustLevel::System);
        assert!(p
            .native_libs
            .iter()
            .any(|l| l.file_name == "libmobileglues.so" && !l.optional));
        // every native lib carries the APK integrity metadata
        for nl in &p.native_libs {
            assert!(nl.expected_size.is_some(), "{} missing size", nl.file_name);
            assert!(nl.expected_sha1.is_some(), "{} missing sha1", nl.file_name);
            assert!(
                nl.expected_sha256.is_some(),
                "{} missing sha256",
                nl.file_name
            );
        }
    }

    #[test]
    fn plugin_stays_in_lockstep_with_renderer_enum() {
        let p = mobileglues_plugin();
        let r = Renderer::MobileGlues;
        assert_eq!(p.id, r.id());
        assert_eq!(p.gl_libname, r.gl_libname());
        let p_env: Vec<(&str, String)> =
            p.env.iter().map(|(k, v)| (k.as_str(), v.clone())).collect();
        assert_eq!(p_env, r.env());
    }

    #[test]
    fn parse_apk_recovers_integrity() {
        // Only run when the bundled APK is present (not in headless CI).
        let apk = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .ancestors()
            .nth(3)
            .map(|p| p.join("mobile_gules_apk/MobileGlues_2.0.0.apk"))
            .filter(|p| p.exists());
        let Some(apk) = apk else {
            eprintln!("skipping parse_apk_recovers_integrity: bundled APK not found");
            return;
        };
        let libs = parse_mobileglues_apk(&apk, Abi::Arm64V8a).unwrap();
        assert_eq!(libs.len(), 3);
        let primary = libs.iter().find(|m| m.primary).unwrap();
        assert_eq!(primary.file_name, "libmobileglues.so");
        // the freshly parsed hashes must equal the embedded inventory
        let embedded = MOBILEGLUES_APK_LIBS
            .iter()
            .find(|m| m.file_name == "libmobileglues.so")
            .unwrap();
        assert_eq!(primary.sha1, embedded.sha1);
        assert_eq!(primary.sha256, embedded.sha256);
        assert_eq!(primary.size, embedded.size);
    }

    #[test]
    fn register_from_apk_refreshes_registry() {
        // Only run when the bundled APK is present (not in headless CI).
        let apk = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .ancestors()
            .nth(3)
            .map(|p| p.join("mobile_gules_apk/MobileGlues_2.0.0.apk"))
            .filter(|p| p.exists());
        let Some(apk) = apk else {
            eprintln!("skipping register_from_apk_refreshes_registry: bundled APK not found");
            return;
        };
        // Fold the APK-parsed plugin into the built-in registry and verify the
        // on-device integrity (size + hashes) is attached to the primary lib.
        let reg = RendererRegistry::builtin();
        let reg = register_mobileglues_from_apk(reg, &apk, Abi::Arm64V8a).unwrap();
        let p = reg.get("mobile_glues").unwrap();
        assert_eq!(p.trust, TrustLevel::System);
        let primary = p
            .native_libs
            .iter()
            .find(|l| l.file_name == "libmobileglues.so")
            .unwrap();
        assert!(!primary.optional);
        assert_eq!(primary.expected_size, Some(6120864));
        assert_eq!(
            primary.expected_sha1.as_deref(),
            Some("4b246f3a0601873b29ab2d22bf63b5962f5ce128")
        );
        assert_eq!(
            primary.expected_sha256.as_deref(),
            Some("3c87948b9b362ad2b6cf48e43ea181014f9999fe4607db0eff8b9db52d385fcd")
        );
    }
}
