//! Emit the cross-language golden fixtures for the adaptive layout (task 9).
//!
//! `crate::display` (Rust) and `ui/AdaptiveLayout.kt` (Kotlin) are hand-ported
//! mirrors: Compose resolves the window size class locally on every
//! recomposition — a rotating device must not pay a JNI crossing per frame — so
//! the two ports have to agree *exactly*. Otherwise the core would report
//! "landscape, 3 columns, navigation rail" in its diagnostics while the UI drew
//! a single column with a bottom bar.
//!
//! This example renders a fixed device matrix with the **Rust** implementation
//! and writes two tab-separated tables:
//!
//! * `app/src/test/resources/display_layout_golden.tsv` — one row per window
//!   geometry with every layout decision derived from it;
//! * `app/src/test/resources/display_orientation_golden.tsv` — the orientation
//!   policy table (settings id → `android:screenOrientation` → the game window
//!   geometry the policy forces).
//!
//! `AdaptiveLayoutParityTest` (Kotlin) replays both tables and asserts the mirror
//! produces identical values, and `scripts/check_layout_parity.py` re-runs this
//! generator to prove the committed fixtures are not stale.
//!
//! ```bash
//! cargo run --example display_layout_golden            # print to stdout
//! cargo run --example display_layout_golden -- --write # update the fixtures
//! ```

use rc_launcher::display::{OrientationPolicy, WindowMetrics};
use rc_launcher::launch::WindowSize;

/// Window geometries every port must agree on.
///
/// Real devices (phone / large phone / foldable / tablet, in *both*
/// orientations) plus every breakpoint edge and the degenerate cases, because a
/// rotation is exactly what walks a device across those edges.
fn geometries() -> Vec<(u32, u32)> {
    let bases: Vec<(u32, u32)> = vec![
        // --- phones ---
        (320, 480), // very small / legacy
        (360, 640), // compact phone
        (392, 872), // Pixel-class reference phone
        (411, 891), // large phone
        (480, 320), // small landscape window (split screen)
        // --- foldables / tablets ---
        (600, 960),   // small tablet, medium width
        (673, 841),   // unfolded foldable
        (800, 1280),  // 7" tablet portrait
        (840, 1120),  // exactly on the expanded edge
        (1280, 800),  // 10" tablet landscape
        (1600, 1000), // desktop-class window
        // --- breakpoint edges (the interesting arithmetic) ---
        (599, 479),
        (600, 480),
        (839, 899),
        (840, 900),
        (599, 900),
        (840, 479),
        // --- degenerate / extreme ---
        (1, 1),
        (1080, 1080), // square
        (10_000, 1),  // clamped extremes
        (10_000, 10_000),
    ];
    let mut out = Vec::with_capacity(bases.len() * 2);
    for (w, h) in bases {
        out.push((w, h));
        // Every geometry also appears rotated: that is the whole point.
        if w != h {
            out.push((h, w));
        }
    }
    out
}

/// Window sizes handed to [`OrientationPolicy::orient`] in the policy fixture.
fn policy_windows() -> Vec<WindowSize> {
    vec![
        WindowSize {
            width: 1280,
            height: 720,
        },
        WindowSize {
            width: 720,
            height: 1280,
        },
        WindowSize {
            width: 1024,
            height: 1024,
        },
        WindowSize {
            width: 854,
            height: 480,
        },
    ]
}

fn metrics_table() -> (String, usize) {
    let mut out = String::from(
        "\
# GENERATED by `cargo run --example display_layout_golden -- --write` — DO NOT EDIT.\n\
#\n\
# The Rust `display::WindowMetrics` implementation is the oracle for the Kotlin\n\
# port (`app/src/main/java/com/rc/launcher/ui/AdaptiveLayout.kt`). Compose\n\
# re-resolves the layout locally on every rotation instead of crossing the JNI\n\
# boundary, so both ports must decide identically.\n\
# `AdaptiveLayoutParityTest` replays this table; `scripts/check_layout_parity.py`\n\
# re-runs the generator and fails when the committed fixture is stale.\n\
#\n\
# width_dp\theight_dp\torientation\twidth_class\theight_class\tlandscape\tshort\
\tnavigation_rail\tinstance_columns\tsettings_columns\tdashboard_columns\
\tcontent_padding_dp\tmax_content_width_dp\n",
    );
    let mut count = 0usize;
    for (w, h) in geometries() {
        let m = WindowMetrics::new(w, h);
        out.push_str(&format!(
            "{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\n",
            m.width_dp,
            m.height_dp,
            m.orientation().id(),
            m.width_class().id(),
            m.height_class().id(),
            m.is_landscape(),
            m.is_short(),
            m.uses_navigation_rail(),
            m.instance_columns(),
            m.settings_columns(),
            m.dashboard_columns(),
            m.content_padding_dp(),
            m.max_content_width_dp(),
        ));
        count += 1;
    }
    (out, count)
}

fn policy_table() -> (String, usize) {
    let mut out = String::from(
        "\
# GENERATED by `cargo run --example display_layout_golden -- --write` — DO NOT EDIT.\n\
#\n\
# The screen-orientation policy table (task 9). `id` is what the launcher\n\
# settings persist and what `LaunchOptions.orientation` accepts; `android`\n\
# is the `android:screenOrientation` / `ActivityInfo.SCREEN_ORIENTATION_*` value\n\
# `MainActivity.applyOrientation` requests; `out_w x out_h` is the game window\n\
# geometry the policy forces for the given `in_w x in_h`.\n\
#\n\
# id\tandroid\tforced\tin_w\tin_h\tout_w\tout_h\n",
    );
    let mut count = 0usize;
    for policy in OrientationPolicy::ALL {
        for window in policy_windows() {
            let oriented = policy.orient(window);
            out.push_str(&format!(
                "{}\t{}\t{}\t{}\t{}\t{}\t{}\n",
                policy.id(),
                policy.android_screen_orientation(),
                policy.forced().map(|o| o.id()).unwrap_or("-"),
                window.width,
                window.height,
                oriented.width,
                oriented.height,
            ));
            count += 1;
        }
    }
    (out, count)
}

fn main() {
    let (metrics, metrics_rows) = metrics_table();
    let (policies, policy_rows) = policy_table();

    if std::env::args().any(|a| a == "--write") {
        // `CARGO_MANIFEST_DIR` = rust/crates/rc-launcher-core
        let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../..")
            .join("app/src/test/resources");
        std::fs::create_dir_all(&dir).expect("create fixture dir");
        let layout = dir.join("display_layout_golden.tsv");
        std::fs::write(&layout, &metrics).expect("write layout fixture");
        let orientation = dir.join("display_orientation_golden.tsv");
        std::fs::write(&orientation, &policies).expect("write orientation fixture");
        println!(
            "wrote {metrics_rows} geometries -> {}\nwrote {policy_rows} policies -> {}",
            layout.display(),
            orientation.display()
        );
    } else {
        print!("{metrics}");
        print!("{policies}");
    }
}
