//! Emit the cross-language golden fixture for the value formatters (task 20).
//!
//! `crate::i18n::number` (Rust) and `RcValueFormat.kt` (Kotlin) are hand-ported
//! mirrors: Compose formats byte sizes / ETAs locally from the catalogue bundle
//! so it does not pay a JNI crossing per label, which means the two ports must
//! agree *exactly* — otherwise the download screen and the launcher log would
//! disagree about the same number.
//!
//! This example renders a fixed matrix of (language, kind, input) cases with the
//! **Rust** implementation and writes it to
//! `app/src/test/resources/i18n_format_golden.tsv`. The Kotlin unit test
//! (`RcValueFormatParityTest`) replays the same matrix and asserts it produces
//! byte-identical text, and `scripts/check_i18n.py` re-runs this generator to
//! prove the committed fixture is not stale.
//!
//! The fixture is a **tab-separated** table rather than JSON on purpose: the
//! Kotlin unit test then needs no JSON dependency at all, and the file diffs
//! line-by-line in review so a wording change shows exactly which renderings it
//! moved.
//!
//! ```bash
//! cargo run --example i18n_format_golden            # print to stdout
//! cargo run --example i18n_format_golden -- --write # update the fixture
//! ```

use rc_launcher::ffi::i18n_format_json;
use serde_json::{json, Value};

/// The inputs every port must agree on. Deliberately full of edge cases: unit
/// boundaries, rounding ties, zero/negative values, unit promotion and the
/// singular/plural switch.
fn cases() -> Vec<Value> {
    let byte_values: Vec<i64> = vec![
        0,
        1,
        512,
        1_023,
        1_024,
        1_025,
        1_536,
        10_240,
        1_048_575,
        1_048_576,
        1_500_000_000,
        1_099_511_627_776,
        // Rounding must promote the unit instead of printing "1024.0 KB".
        1_048_540,
        1_073_741_823,
        // Negative byte counts clamp to zero rather than wrapping.
        -1,
    ];
    let durations: Vec<i64> = vec![
        0, 1, 2, 59, 60, 61, 90, 119, 120, 200, 3_600, 3_601, 3_605, 3_660, 86_400, 90_061, -200,
        -1,
    ];
    let decimals: Vec<f64> = vec![
        0.0, 0.04, -0.04, 1.25, 1.35, 2.5, 3.5, -2.5, 12.345, 1234.5678, 99.95, -12.34,
    ];
    let ints: Vec<i64> = vec![
        0,
        7,
        999,
        1_000,
        12_345,
        1_234_567,
        -1_234_567,
        i64::MAX,
        i64::MIN,
    ];

    let mut out = Vec::new();
    for tag in ["zh-CN", "zh-Hant", "en"] {
        for &v in &byte_values {
            out.push(json!({ "kind": "bytes", "value": v, "language": tag }));
            out.push(json!({ "kind": "rate", "value": v, "language": tag }));
        }
        for &v in &durations {
            out.push(json!({ "kind": "duration", "value": v, "language": tag }));
            out.push(json!({ "kind": "duration", "value": v, "parts": 1, "language": tag }));
            out.push(json!({ "kind": "duration", "value": v, "parts": 4, "language": tag }));
            out.push(json!({ "kind": "eta", "value": v, "language": tag }));
            out.push(json!({ "kind": "relative", "value": v, "language": tag }));
        }
        for &v in &decimals {
            for digits in [0u64, 1, 2] {
                out.push(
                    json!({ "kind": "decimal", "value": v, "digits": digits, "language": tag }),
                );
                out.push(
                    json!({ "kind": "percent", "value": v, "digits": digits, "language": tag }),
                );
            }
        }
        for &v in &ints {
            out.push(json!({ "kind": "int", "value": v, "language": tag }));
        }
        for (done, total) in [
            (0i64, 0i64),
            (1, 4),
            (3, 4),
            (1, 3),
            (7, 7),
            (1_048_576, 4_194_304),
        ] {
            out.push(json!({
                "kind": "ratio", "value": done, "total": total, "digits": 1, "language": tag
            }));
            out.push(json!({
                "kind": "byte_progress", "value": done, "total": total, "language": tag
            }));
        }
        for v in [0.0f64, 59.94, 60.0, 30.05, 144.0] {
            out.push(json!({ "kind": "fps", "value": v, "language": tag }));
        }
    }
    out
}

/// One TSV field: `-` when the request does not carry that knob.
fn field(request: &Value, name: &str) -> String {
    match request.get(name) {
        Some(Value::Number(n)) => n.to_string(),
        // `Value::to_string` would keep the JSON quotes; the TSV wants the text.
        Some(Value::String(s)) => s.clone(),
        Some(other) => other.to_string(),
        None => "-".to_string(),
    }
}

fn main() {
    let header = "\
# GENERATED by `cargo run --example i18n_format_golden -- --write` \u{2014} DO NOT EDIT.\n\
#\n\
# The Rust `i18n::number` implementation is the oracle for the Kotlin port\n\
# (`app/src/main/java/com/rc/launcher/ui/i18n/RcValueFormat.kt`). Compose formats\n\
# byte sizes / ETAs locally from the catalogue bundle instead of paying a JNI\n\
# crossing per label, so the two ports must render every value identically.\n\
# `RcValueFormatParityTest` replays this table; `scripts/check_i18n.py` re-runs\n\
# the generator and fails when the committed fixture is stale.\n\
#\n\
# language\tkind\tvalue\ttotal\tdigits\tparts\texpected\n";

    let mut out = String::from(header);
    let mut count = 0usize;
    for request in cases() {
        let rendered = i18n_format_json(&request);
        assert_eq!(
            rendered["supported"], true,
            "unsupported kind in the fixture: {request}"
        );
        let text = rendered["text"].as_str().unwrap_or_default();
        // A golden file full of unresolved placeholders would be worse than none.
        assert!(!text.is_empty(), "empty rendering for {request}");
        assert!(
            !text.contains('{'),
            "unresolved placeholder for {request}: {text}"
        );
        // Tabs / newlines would break the format; none of our copy has them.
        assert!(
            !text.contains('\t') && !text.contains('\n'),
            "rendering contains a field separator: {text:?}"
        );
        out.push_str(&format!(
            "{}\t{}\t{}\t{}\t{}\t{}\t{}\n",
            field(&request, "language"),
            field(&request, "kind"),
            field(&request, "value"),
            field(&request, "total"),
            field(&request, "digits"),
            field(&request, "parts"),
            text,
        ));
        count += 1;
    }

    if std::env::args().any(|a| a == "--write") {
        // `CARGO_MANIFEST_DIR` = rust/crates/rc-launcher-core
        let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../..")
            .join("app/src/test/resources");
        std::fs::create_dir_all(&dir).expect("create fixture dir");
        let path = dir.join("i18n_format_golden.tsv");
        std::fs::write(&path, &out).expect("write fixture");
        println!("wrote {count} cases -> {}", path.display());
    } else {
        print!("{out}");
    }
}
