/* rc_launcher.h - C ABI for the RC Launcher Rust core.
 * Generated by cbindgen from src/capi.rs. Do not edit by hand.
 * Mirrors MCTier's libeasytier_ffi.so: a thin C contract consumed by the JNI
 * wrapper (ffi.rs) and any other native caller. */

/* Generated by cbindgen. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Callback invoked for every published event.
 *
 * `json` is a NUL-terminated UTF-8 string (owned by the callee for the
 * duration of the call); `userdata` is the pointer passed to
 * [`rc_event_bus_subscribe`] so the C side can recover its own context (the
 * classic `void*` userdata idiom).
 */
typedef void (*RcEventCallback)(const char*, void*);

/**
 * Subscribe a C event callback. `cb` is invoked with a NUL-terminated JSON
 * string and the `userdata` pointer for every published event. Returns `1` if
 * a previous callback was replaced, `0` otherwise.
 *
 * # Safety
 * `cb` must be a valid `extern "C"` function pointer. `userdata` must outlive
 * the subscription (until [`rc_event_bus_unsubscribe`] is called).
 */
int rc_event_bus_subscribe(RcEventCallback cb, void *userdata);

/**
 * Remove the current C event callback. Subsequent publishes become no-ops.
 */
void rc_event_bus_unsubscribe(void);

/**
 * Whether a callback is currently subscribed (`1` / `0`).
 */
int rc_event_bus_has_sink(void);

/**
 * Publish a pre-serialised JSON event from the C side (e.g. to replay a log).
 * Returns `1` on success, `0` if `json` is null or not valid event JSON.
 *
 * # Safety
 * `json` must be a NUL-terminated UTF-8 string.
 */
int rc_event_bus_publish(const char *json);

/**
 * C mirror of the JNI `runAsync`: spawn a background job that reports through
 * the event bus and returns immediately. `spec_json` is the same JSON accepted
 * by the JNI `runAsync`. Returns a NUL-terminated JSON string
 * `{ "ok": bool, "scope": string }`; the caller must free it with
 * [`rc_string_free`].
 *
 * # Safety
 * `spec_json` must be a NUL-terminated UTF-8 string.
 */
char *rc_run_async(const char *spec_json);

/**
 * Cancel a running async job by scope. Returns `1` if a job was found (and will
 * observe the flag on its next poll), `0` otherwise.
 *
 * # Safety
 * `scope` must be a NUL-terminated UTF-8 string.
 */
int rc_cancel_async(const char *scope);

/**
 * Spawn a real download job (task 2 ⇄ task 10 integration): a batch of
 * download tasks from `spec_json` is driven by the resumable download
 * manager and reports progress / lifecycle / error events through the
 * subscribed callback. Returns a NUL-terminated JSON string
 * `{ "ok": bool, "scope": string }`; free it with `rc_string_free`.
 *
 * # Safety
 * `spec_json` must be a NUL-terminated UTF-8 string.
 */
char *rc_download_async(const char *spec_json);


/**
 * Free a string returned by [`rc_run_async`]. Passing a null pointer is a
 * no-op.
 *
 * # Safety
 * `s` must be a pointer returned by [`rc_run_async`] (or null).
 */
void rc_string_free(char *s);
